services:
  app:
    image: esi_2023:latest
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: postgres:15.4
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: