services:
  app:
    image: esi_2023:latest
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data: